const BoardData = [
  {
    id: 0,
    title: "test title",
    writer: "test writer", //nickname
    email: "test0@test.com",
    content: "I success!!",
    timestamp: new Date().getTime(),
    type: 0,
    comments: [
      {
        writer: "apple",
        email: "test3@test.com",
        msg: "congratulation~",
        timestamp: new Date().getTime(),
      },
      {
        writer: "apple",
        email: "test12@test.com",
        msg: "계속해서 좋은 일이 있길 바랄게요!",
        timestamp: new Date().getTime(),
      },
      {
        writer: "apple",
        email: "test11@test.com",
        msg: "훌륭한 작업이네요!",
        timestamp: new Date().getTime(),
      },
    ],
  },
  {
    id: 1,
    title: "test title1",
    writer: "test writer1",
    email: "test1@test.com",
    content: "it is good1",
    timestamp: new Date().getTime(),
    type: 1,
    comments: [
      {
        writer: "apple",
        email: "test4@test.com",
        msg: "축하드려요~",
        timestamp: new Date().getTime(),
      },
      {
        writer: "apple",
        email: "test10@test.com",
        msg: "좋은 일이 계속되길 바랍니다!",
        timestamp: new Date().getTime(),
      },
    ],
  },
  {
    id: 2,
    title: "test title2",
    writer: "test writer2",
    email: "test2@test.com",
    content: "it is good2",
    timestamp: new Date().getTime(),
    type: 0,
    comments: [
      {
        writer: "apple",
        email: "test5@test.com",
        msg: "잘하셨어요!",
        timestamp: new Date().getTime(),
      },
    ],
  },
  {
    id: 3,
    title: "test title3",
    writer: "test writer3",
    email: "test3@test.com",
    content: "it is good3",
    timestamp: new Date().getTime(),
    type: 1,
    comments: [],
  },
  {
    id: 4,
    title: "test title4",
    writer: "test writer4",
    email: "test4@test.com",
    content: "it is good4",
    timestamp: new Date().getTime(),
    type: 0,
    comments: [
      {
        writer: "apple",
        email: "test7@test.com",
        msg: "훌륭해요!",
        timestamp: new Date().getTime(),
      },
      {
        writer: "apple",
        email: "test6@test.com",
        msg: "멋져요!",
        timestamp: new Date().getTime(),
      },
    ],
  },
  {
    id: 5,
    title: "test title5",
    writer: "test writer5",
    email: "test5@test.com",
    content: "it is good5",
    timestamp: new Date().getTime(),
    type: 1,
    comments: [
      {
        writer: "apple",
        email: "test8@test.com",
        msg: "좋은 결과를 기대합니다!",
        timestamp: new Date().getTime(),
      },
    ],
  },
  {
    id: 6,
    title: "test title6",
    writer: "test writer6",
    email: "test6@test.com",
    content: "it is good6",
    timestamp: new Date().getTime(),
    type: 0,
    comments: [
      {
        writer: "apple",
        email: "test9@test.com",
        msg: "계속해서 좋은 성과를 기대할게요!",
        timestamp: new Date().getTime(),
      },
    ],
  },
  {
    id: 7,
    title: "test title7",
    writer: "test writer7",
    email: "test7@test.com",
    content: "it is good7",
    timestamp: new Date().getTime(),
    type: 1,
    comments: [],
  },
  {
    id: 8,
    title: "test title8",
    writer: "test writer8",
    email: "test8@test.com",
    content: "it is good8",
    timestamp: new Date().getTime(),
    type: 0,
    comments: [],
  },
  {
    id: 9,
    title: "test title9",
    writer: "test writer9",
    email: "test9@test.com",
    content: "it is good9",
    timestamp: new Date().getTime(),
    type: 1,
    comments: [],
  },
];

export default BoardData;
